server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.1.2:3306/book_store
    username: remote
    password: remote
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
aop:
  logging:
    pointcuts: execution(* np.com.oskarshrestha.bookstorebackend.controller..*(..)),execution(* np.com.oskarshrestha.bookstorebackend.service..*(..)),execution(* np.com.oskarshrestha.bookstorebackend.repository..*(..))